# Copyright (c) 2024 Sebastien Rousseau
#
# Licensed under the GNU AGPLv3 License. See LICENSE file in the project root
# for full license information.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class FidoAssertionDto(BaseModel):
    """Immutable Data Transfer Object securely encapsulating a FIDO2 Biometric Assertion.

    This DTO represents the exact hardware-signed payload returned by
    either the local Secure Enclave or the remote QR bridge. It is passed
    from `uon.auth` cleanly into the `uon.transport` layer.
    """

    credential_id: bytes = Field(
        ..., description="The raw credential ID of the resident passkey used for the assertion."
    )
    client_data: bytes = Field(
        ..., description="The serialized clientDataJSON generated by the Authenticator."
    )
    auth_data: bytes = Field(
        ..., description="The binary authenticatorData conveying the signature counter and bits."
    )
    signature: bytes = Field(
        ..., description="The ECDSA (or other) signature over the challenge and client data."
    )

    model_config = ConfigDict(frozen=True, strict=True)


class SecureEnvelopeDto(BaseModel):
    """The complete execution envelope encapsulating a signed Zero-Trust execution command.

    This exact schema is serialized to JSON and wrapped inside the
    `__UON_EXEC__ <b64>` parametric tunnel during SSH transport. Look to
    `uon_verifier.py` on the target for the matching inverse schema logic.
    """

    session_id: str = Field(
        ..., description="The unique Type 4 UUID identifying this execution session."
    )
    command: list[str] = Field(
        ..., description="The strict POSIX argument array (e.g. ['cat', '/etc/hostname'])."
    )
    assertion: FidoAssertionDto = Field(
        ..., description="The cryptographic WebAuthn assertion proving physical presence."
    )

    model_config = ConfigDict(frozen=True, strict=True)
